title: <p align="center"> Mykayla Graham </p>

logo: "IMG_1685.png.jpeg"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/mykayla-graham-230894213">LinkedIn</a> |
  <a href="https://github.com/mykaylagraham">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently a Junior at North Carolina Central University. I am majoring in Computer Science with a concentration in Cyber Security. 
  <br><br>
  </p>
  
